/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.cografibilgisistemleri.omerSahin;

import java.applet.Applet;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import java.awt.geom.Line2D;
import javax.swing.JOptionPane;


public class bilgiSistemi extends javax.swing.JFrame {
    Graphics sekil ;
    Graphics2D g;
    Line2D line;
    public bilgiSistemi() {
        
        initComponents();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelGenislik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        panelYukseklik = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        noktaX1 = new javax.swing.JTextField();
        noktaY1 = new javax.swing.JTextField();
        noktaButon = new javax.swing.JButton();
        inceNokta = new javax.swing.JRadioButton();
        ortaNokta = new javax.swing.JRadioButton();
        kalinNokta = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        inceCizgi = new javax.swing.JRadioButton();
        ortaCizgi = new javax.swing.JRadioButton();
        kalinCizgi = new javax.swing.JRadioButton();
        cizgiButon = new javax.swing.JButton();
        panel = new java.awt.Panel();
        jLabel14 = new javax.swing.JLabel();
        poligonCiz = new javax.swing.JButton();
        incePoligon = new javax.swing.JRadioButton();
        ortaPoligon = new javax.swing.JRadioButton();
        kalinPoligon = new javax.swing.JRadioButton();
        temizleButon = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coğrafi Bilgi Sistemleri");

        jLabel1.setText("Çizim Ekranı ");

        jButton1.setText("Ekrana Getir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Yükseklik :");

        jLabel3.setText("Genişlik :");

        jLabel4.setText("Nokta :");

        jLabel5.setText("x1:");

        jLabel6.setText("y1:");

        noktaButon.setText("Çiz");
        noktaButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noktaButonActionPerformed(evt);
            }
        });

        buttonGroup1.add(inceNokta);
        inceNokta.setText("İnce");

        buttonGroup1.add(ortaNokta);
        ortaNokta.setText("Orta");

        buttonGroup1.add(kalinNokta);
        kalinNokta.setText("Kalın");

        jLabel7.setText("Çizgi :");

        buttonGroup1.add(inceCizgi);
        inceCizgi.setText("İnce");

        buttonGroup1.add(ortaCizgi);
        ortaCizgi.setText("Orta");
        ortaCizgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ortaCizgiActionPerformed(evt);
            }
        });

        buttonGroup1.add(kalinCizgi);
        kalinCizgi.setText("Kalın");

        cizgiButon.setText("Çiz");
        cizgiButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cizgiButonActionPerformed(evt);
            }
        });

        panel.setBackground(new java.awt.Color(204, 255, 255));
        panel.setVisible(false);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel14.setText("Poligon :");

        poligonCiz.setText("Çiz");
        poligonCiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonCizActionPerformed(evt);
            }
        });

        buttonGroup1.add(incePoligon);
        incePoligon.setText("İnce");

        buttonGroup1.add(ortaPoligon);
        ortaPoligon.setText("Orta");

        buttonGroup1.add(kalinPoligon);
        kalinPoligon.setText("Kalın");

        temizleButon.setText("Temizle");
        temizleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizleButonActionPerformed(evt);
            }
        });

        jLabel8.setText("Ömer Faruk Şahin");

        jLabel9.setText("1821012058");

        jButton2.setText("PROGRAMI KAPAT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(kalinNokta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(noktaButon))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jButton1))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(ortaNokta)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noktaY1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(inceNokta)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(noktaX1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(panelGenislik, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(panelYukseklik, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cizgiButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(temizleButon)
                                .addGap(8, 8, 8))
                            .addComponent(poligonCiz, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(157, 157, 157)
                        .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ortaCizgi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inceCizgi, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kalinCizgi)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incePoligon)
                            .addComponent(ortaPoligon)
                            .addComponent(kalinPoligon)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton2)))
                .addContainerGap(817, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(noktaX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(inceNokta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(ortaNokta)
                                            .addComponent(jLabel6)
                                            .addComponent(noktaY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(panelYukseklik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(panelGenislik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))))
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kalinNokta)
                    .addComponent(noktaButon))
                .addGap(19, 19, 19)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inceCizgi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ortaCizgi)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kalinCizgi, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cizgiButon)))
                .addGap(11, 11, 11)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incePoligon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ortaPoligon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kalinPoligon)
                    .addComponent(poligonCiz))
                .addGap(37, 37, 37)
                .addComponent(temizleButon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poligonCizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonCizActionPerformed
        sekil=(Graphics2D) panel.getGraphics();
        g=(Graphics2D) panel.getGraphics();
        if(incePoligon.isSelected()){
            int kenarSayisi = Integer.parseInt(JOptionPane.showInputDialog("Poligon Kenar Sayısı Giriniz"));
             int xDizi[] = new int[kenarSayisi];
             int yDizi[] = new int[kenarSayisi];
             int x, y;
             g.setStroke(new BasicStroke(2));
                    for (int i = 0; i < kenarSayisi; i++) {
                        x = Integer.parseInt(JOptionPane.showInputDialog(null, "x koordinatı"));
                        y = Integer.parseInt(JOptionPane.showInputDialog(null, "y koordinatı"));
                        xDizi[i] = x;
                        yDizi[i] = y;
                    }
          g.drawPolygon(xDizi, yDizi, kenarSayisi);
                    
        }
        else if(ortaPoligon.isSelected()){
            int kenarSayisi = Integer.parseInt(JOptionPane.showInputDialog("Poligon Kenar Sayısı Giriniz"));
             int xDizi[] = new int[kenarSayisi];
             int yDizi[] = new int[kenarSayisi];
             int x, y;
             g.setStroke(new BasicStroke(4));
                    for (int i = 0; i < kenarSayisi; i++) {
                        x = Integer.parseInt(JOptionPane.showInputDialog(null, "x koordinatı"));
                        y = Integer.parseInt(JOptionPane.showInputDialog(null, "y koordinatı"));
                        xDizi[i] = x;
                        yDizi[i] = y;
                    }
          g.drawPolygon(xDizi, yDizi, kenarSayisi);
            
        }
        else if(kalinPoligon.isSelected()){
            int kenarSayisi = Integer.parseInt(JOptionPane.showInputDialog("Poligon Kenar Sayısı Giriniz"));
             int xDizi[] = new int[kenarSayisi];
             int yDizi[] = new int[kenarSayisi];
             int x, y;
             g.setStroke(new BasicStroke(6));
                    for (int i = 0; i < kenarSayisi; i++) {
                        x = Integer.parseInt(JOptionPane.showInputDialog(null, "x koordinatı"));
                        y = Integer.parseInt(JOptionPane.showInputDialog(null, "y koordinatı"));
                        xDizi[i] = x;
                        yDizi[i] = y;
                    }
          g.drawPolygon(xDizi, yDizi, kenarSayisi);
        }

    }//GEN-LAST:event_poligonCizActionPerformed

    private void cizgiButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cizgiButonActionPerformed
        sekil=(Graphics2D) panel.getGraphics();
        g=(Graphics2D) panel.getGraphics();
        if(inceCizgi.isSelected()){
            int x1,y1,x2,y2,xn,yn,geciciX,geciciY;

            String sayi = JOptionPane.showInputDialog("Kaç çizgi çizilecek? ");
            int cizgiSayisi = Integer.parseInt(sayi);
            x1=Integer.parseInt(JOptionPane.showInputDialog(null,"x1 koordinatını gir"));
            y1=Integer.parseInt(JOptionPane.showInputDialog(null,"y1 koordinatını gir"));
            x2=Integer.parseInt(JOptionPane.showInputDialog(null,"x2 koordinatını gir"));
            y2=Integer.parseInt(JOptionPane.showInputDialog(null,"y2 koordinatını gir"));
            geciciX=x2;geciciY=y2;
            sekil.drawLine(x1, y1, x2, y2);
            for (int i = 0; i <cizgiSayisi-1; i++) {
                xn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki x kordinatını gir"));
                yn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki y kordinatını gir"));
                sekil.drawLine(geciciX,geciciY,xn,yn);
                geciciX=xn;geciciY=yn;
            }
        }
        else if(ortaCizgi.isSelected()){
   
           int x1,y1,x2,y2,xn,yn,geciciX,geciciY;

            String sayi = JOptionPane.showInputDialog("Kaç çizgi çizilecek? ");
            int cizgiSayisi = Integer.parseInt(sayi);
            x1=Integer.parseInt(JOptionPane.showInputDialog(null,"x1 koordinatını gir"));
            y1=Integer.parseInt(JOptionPane.showInputDialog(null,"y1 koordinatını gir"));
            x2=Integer.parseInt(JOptionPane.showInputDialog(null,"x2 koordinatını gir"));
            y2=Integer.parseInt(JOptionPane.showInputDialog(null,"y2 koordinatını gir"));
            geciciX=x2;geciciY=y2;
            g.setStroke(new BasicStroke(5));
            g.drawLine(x1, y1, x2, y2);
            for (int i = 0; i <cizgiSayisi-1; i++) {
                xn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki x kordinatını gir"));
                yn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki y kordinatını gir"));
                g.setStroke(new BasicStroke(5));
                g.drawLine(geciciX,geciciY,xn,yn);
                geciciX=xn;geciciY=yn;
            }
        }
        
        else if(kalinCizgi.isSelected()){
                int x1,y1,x2,y2,xn,yn,geciciX,geciciY;

            String sayi = JOptionPane.showInputDialog("Kaç çizgi çizilecek? ");
            int cizgiSayisi = Integer.parseInt(sayi);
            x1=Integer.parseInt(JOptionPane.showInputDialog(null,"x1 koordinatını gir"));
            y1=Integer.parseInt(JOptionPane.showInputDialog(null,"y1 koordinatını gir"));
            x2=Integer.parseInt(JOptionPane.showInputDialog(null,"x2 koordinatını gir"));
            y2=Integer.parseInt(JOptionPane.showInputDialog(null,"y2 koordinatını gir"));
            geciciX=x2;geciciY=y2;
            g.setStroke(new BasicStroke(7));
            g.drawLine(x1, y1, x2, y2);
            for (int i = 0; i <cizgiSayisi-1; i++) {
                xn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki x kordinatını gir"));
                yn=Integer.parseInt(JOptionPane.showInputDialog(null,"Bir sonraki y kordinatını gir"));
                g.setStroke(new BasicStroke(7));
                g.drawLine(geciciX,geciciY,xn,yn);
                geciciX=xn;geciciY=yn;
            }
        
        }
    }//GEN-LAST:event_cizgiButonActionPerformed

    private void ortaCizgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ortaCizgiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ortaCizgiActionPerformed

    private void noktaButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noktaButonActionPerformed
        sekil=(Graphics2D) panel.getGraphics();
        if(inceNokta.isSelected()){
            sekil.fillOval(Integer.parseInt(noktaX1.getText()),Integer.parseInt(noktaY1.getText()),5,5);
        }
        else if(ortaNokta.isSelected()){
            sekil.fillOval(Integer.parseInt(noktaX1.getText()),Integer.parseInt(noktaY1.getText()),10,10);
        }
        else if(kalinNokta.isSelected()){
            sekil.fillOval(Integer.parseInt(noktaX1.getText()),Integer.parseInt(noktaY1.getText()),15,15);
        }
    }//GEN-LAST:event_noktaButonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        panelEkle(panelGenislik.getText(),panelYukseklik.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void temizleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizleButonActionPerformed
        panel.repaint();
    }//GEN-LAST:event_temizleButonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bilgiSistemi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bilgiSistemi().setVisible(true);
                
            }
        });
    }
    
   /* public void paint(Graphics g){
     super.paint(g);
     g.setColor(Color.red);
     g.drawRect(300, 400, 50, 100);
     
}*/
    
    
    public void panelEkle(String genislik,String yukseklik){
        panel.setSize(Integer.valueOf(genislik),Integer.valueOf(yukseklik));
        panel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cizgiButon;
    private javax.swing.JRadioButton inceCizgi;
    private javax.swing.JRadioButton inceNokta;
    private javax.swing.JRadioButton incePoligon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton kalinCizgi;
    private javax.swing.JRadioButton kalinNokta;
    private javax.swing.JRadioButton kalinPoligon;
    private javax.swing.JButton noktaButon;
    private javax.swing.JTextField noktaX1;
    private javax.swing.JTextField noktaY1;
    private javax.swing.JRadioButton ortaCizgi;
    private javax.swing.JRadioButton ortaNokta;
    private javax.swing.JRadioButton ortaPoligon;
    private java.awt.Panel panel;
    private javax.swing.JTextField panelGenislik;
    private javax.swing.JTextField panelYukseklik;
    private javax.swing.JButton poligonCiz;
    private javax.swing.JButton temizleButon;
    // End of variables declaration//GEN-END:variables
}

